### ISSUE TITLE
Can not determine project directory

### ISSUE THREAD

**Issue by buraksenkus** [brianmc95/OpenCV2X#21]
Hi sir,
I'm facing a problem when I'm trying to enable **WITH_SIMULTE** option.

First of all, here are my steps:
- I configured and ran make Omnet++ 5.6.2.
- I ran `make inet`, `make vanetza`, `make simulte` and `cd extern/veins && ./configure && make` in order. These steps have been completed successfully.
- Then I ran `cmake ..` in **OpenCV2X/build** directory. Its output was like below.
```
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OmnetPP: /home/bsenkus/simulator/omnetpp-5.6.2/include (found suitable version "5.6.2", minimum required is "5.4") 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.5", minimum required is "3") 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.71") found components: date_time 
-- GeographicLib: using lookup code by Vanetza
-- Found GeographicLib: /usr/include (found suitable version "1.50.1", minimum required is "1.50.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CryptoPP: /usr/include (found suitable version "5.6.4", minimum required is "5.6.4") 
CMake Warning (dev) at /usr/local/lib/cmake/Vanetza/CompatOpenSSLTargets.cmake:6 (message):
  Call find_package(OpenSSL ...) beforehand for backward compatibilility
Call Stack (most recent call first):
  /usr/local/lib/cmake/Vanetza/VanetzaConfig.cmake:61 (include)
  CMakeLists.txt:20 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- SimuLTE integration disabled
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.59") found components: date_time system 
-- Enable Veins integration
-- Enable INET integration
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.5") 
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.5") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
-- pybind11 v2.2.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bsenkus/simulator/OpenCV2X/build
```
After that, I tried to enable **WITH_SIMULTE** option. But when I set it and try to run cmake again it gives below error.
```
-- GeographicLib: using lookup code by Vanetza
CMake Warning (dev) at /usr/local/lib/cmake/Vanetza/CompatOpenSSLTargets.cmake:6 (message):
  Call find_package(OpenSSL ...) beforehand for backward compatibilility
Call Stack (most recent call first):
  /usr/local/lib/cmake/Vanetza/VanetzaConfig.cmake:61 (include)
  CMakeLists.txt:20 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- opp_cmake generated following error log
CMake Error at cmake/ImportOppTarget.cmake:24 (message):
  Traceback (most recent call last):

    File "opp_cmake.py", line 325, in <module>
      main()
    File "opp_cmake.py", line 317, in main
      target = parse_opp_makefile(makefile)
    File "opp_cmake.py", line 285, in parse_opp_makefile
      handler = FlagsHandler(makefile, find_opp_configfile())
    File "opp_cmake.py", line 173, in __init__
      self._project = OmnetProject(makefile)
    File "opp_cmake.py", line 17, in __init__
      self.root_directory = self.lookup_project_directory()
    File "opp_cmake.py", line 33, in lookup_project_directory
      raise ValueError("Can not determine project directory for ${self.makefile}")

  ValueError: Can not determine project directory for ${self.makefile}

Call Stack (most recent call first):
  CMakeLists.txt:31 (import_opp_target)


CMake Error at cmake/ImportOppTarget.cmake:25 (message):
  import_opp_target for lte aborted due to above opp_cmake error
Call Stack (most recent call first):
  CMakeLists.txt:31 (import_opp_target)


-- Configuring incomplete, errors occurred!
See also "/home/bsenkus/simulator/OpenCV2X/build/CMakeFiles/CMakeOutput.log".
See also "/home/bsenkus/simulator/OpenCV2X/build/CMakeFiles/CMakeError.log".
```
I could not understand the problem exactly. Thanks for your help in advance!

**Comment by buraksenkus** [comment]
I have solved the problem. Let me briefly summarize the situation in case others may experience the same problem again.
Some time ago I cloned and built the repository on a different computer. I rebuilt over the files that currently exist on a different computer. As far as I understand it, the directories of some files were saved statically during the previous build process and that was the point that led to the problem. **The problem disappeared when I cloned the repository from scratch and did the make steps cleanly.**
Since have I solved the problem, I'm closing the issue.
